### PR TITLE
Update to 2.7.0 NEI/更新至2.7.0

### LINKED ISSUE #17395: NotEnoughCharacters not adapted
### Your GTNH Discord Username

 XeonKA

### Your Pack Version

2.7.0 beta1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation
Install [NotEnoughCharacters](https://github.com/GTNewHorizons/NotEnoughCharacters)
Searching in nei search bar and AE2 search bar in Chinese Pinyin(For example,niantukuai-->Clay)should display what I want.
QQ20240921-104449

### The Reality

Both didn't display.

QQ20240921-104152
QQ20240921-104631

[NotEnoughItems#507](https://github.com/GTNewHorizons/NotEnoughItems/issues/507)mentioned [NeverEnoughCharacters](https://github.com/vfyjxf/NeverEnoughCharacters),but it died too.

### Your Proposal

Update NotEnoughCharacters to adapt with the latest version NEI and AE2.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by ArtherCasan**
* 解决[issues 17395](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17395)

主要改动由银月月和vfyjxf_做出，本PR根据最新NEI API的变动进行了修改
已在最新2.7.0-beta-1上测试通过

* close [issues 17395](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17395)
* have been tested and worked in 2.7.0-beta-1.
HN@1AT)M9MMA5}DTC{$E~M0

### CODE REVIEW

**Comment by XeonKA** [comment]
@miozune

**Comment by slprime** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/issues/507 - author recommended use another mod

**Comment by XeonKA** [comment]
> [GTNewHorizons/NotEnoughItems#507](https://github.com/GTNewHorizons/NotEnoughItems/issues/507) - author recommended use another mod

Page not found

**Comment by slprime** [comment]
hm...

**Comment by slprime** [comment]
your code will not work correctly. Need change NecharSearchFilter. For each prefix needs its own NecharSearchProvider with getMatchingLanguages method. 

P.S. I can create PR, but need user for testing because i don't know chinese write rules

**Comment by ArtherCasan** [comment]
> your code will not work correctly. Need change NecharSearchFilter. For each prefix needs its own NecharSearchProvider with getMatchingLanguages method.
> 
> P.S. I can create PR, but need user for testing because i don't know chinese write rules

sure, just do that. I'll do my best to help you.
Thank you very much!

**Comment by slprime** [comment]
> > your code will not work correctly. Need change NecharSearchFilter. For each prefix needs its own NecharSearchProvider with getMatchingLanguages method.
> > P.S. I can create PR, but need user for testing because i don't know chinese write rules
> 
> sure, just do that. I'll do my best to help you. Thank you very much!

https://github.com/GTNewHorizons/NotEnoughCharacters/pull/2 - check PR

**Comment by ArtherCasan** [comment]
> > > your code will not work correctly. Need change NecharSearchFilter. For each prefix needs its own NecharSearchProvider with getMatchingLanguages method.
> 
> > > P.S. I can create PR, but need user for testing because i don't know chinese write rules
> 
> > 
> 
> > sure, just do that. I'll do my best to help you. Thank you very much!
> 
> 
> 
> https://github.com/GTNewHorizons/NotEnoughCharacters/pull/2 - check PR

Thank you! I will test it in daytime.(0:48 now)

edit: I've tested all the search methods and there are no problems, thank you for your help.

**Comment by ArtherCasan** [comment]
All features have been done in PR #2

**Pull request closed without merging**
